language: node_js
node_js:
  - "9"
cache:
  yarn: true
  directories:
    - "node_modules"
    - "$HOME/.cargo"
git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustup || (curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y)
  - rustup install nightly
  - rustup default nightly
  - rustup show
  - rustup target add wasm32-unknown-unknown
  - which cargo-web || cargo install cargo-web
script:
  - npm run build
notifications:
    slack: texdocs:LTGOUYfJwMJ95Xk8l5eZbVOF