language: node_js
cache:
  yarn: true
  cargo: true
  directories:
    - "node_modules"
before_install:
  - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
before_script:
  - which rustup || (curl https://sh.rustup.rs -sSf | sh --channel=nightly)
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup target add wasm32-unknown-unknown
  - (which rustfmt && cargo fmt --version) || cargo install rustfmt-nightly --force
  - which cargo-web || cargo install cargo-web
script:
  - npm run build